
const strings = {
    en: 'The quick brown fox jumps over the lazy dog.',
    jp: 'イロハニホヘト チリヌルヲ ワカヨタレソ ツネナラム',
    pt: 'O próximo vôo à noite sobre o Atlântico, põe freqüentemente o único médico.',
    fr: 'Les naïfs ægithales hâtifs pondant à Noël où il gèle sont sûrs d\'être déçus en voyant leurs drôles d\'œufs abîmés.',
    sv: 'Flygande bäckasiner söka strax hwila på mjuka tuvor.',
    dk: 'Quizdeltagerne spiste jordbær med fløde',
    el: 'ξεσκεπάζω την ψυχοφθόρα βδελυγμία',
    tr: 'Pijamalı hasta, yağız şoföre çabucak güvendi.',
    ru: 'Съешь же ещё этих мягких французских булок да выпей чаю',
    hu: 'Árvíztűrő tükörfúrógép',
    pl: 'Pchnąć w tę łódź jeża lub ośm skrzyń fig',
    cz: 'Mohu jíst sklo, neublíží mi.',
    ar: 'أنا قادر على أكل الزجاج و هذا لا يؤلمني.',
    et: 'Ma võin klaasi süüa, see ei tee mulle midagi.',
    lt: 'Aš galiu valgyti stiklą ir jis manęs nežeidžia.',
    bg: 'Мога да ям стъкло, то не ми вреди.',
    is: 'Ég get etið gler án þess að meiða mig.',
    he: 'אני יכול לאכול זכוכית וזה לא מזיק לי.',
    fa: '.من می توانم بدونِ احساس درد شيشه بخورم',
    uk: 'Я можу їсти скло, і воно мені не зашкодить.',
    vi: 'Tôi có thể ăn thủy tinh mà không hại gì.',
    kk: 'қазақша',
    lv: 'Es varu ēst stiklu, tas man nekaitē.',
    mt: 'Nista\' niekol il-ħġieġ u ma jagħmilli xejn.',
    th: 'ฉันกินกระจกได้ แต่มันไม่ทำให้ฉันเจ็บ',
};

export default strings;